# In this notebook, fudamental concepts of tensorflow concepts are described



*   Intro to Tensors
*   Getting information from tensors
*   Manupulating tensors
*   Tensor & NumPy
*   Using @tf.function(a way to speed up your regular Python functions)
*   Exercises






Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check dimension of vector
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
#Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we have created so far

*Scalar: a single number

*Vector: a number with direction (e.g. wind speed and direction)

*Matrix: a 2-dimensional array of numbers

*Tensor: a n-dimensional array of numbers where n can be any number, a 0-dimensional tensor is a scalar, 1-dimensional is a vector.

# Creating tensors with tf.Variable

In [12]:
#Create same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try change one of the element in the changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
#Let's try change unchangeable tensor
unchangeable_tensor[0].assign(2)
unchangeable_tensor

AttributeError: ignored

##Creating random tensors

Random tensors are tensor of some arbitary size which contain some random numbers



In [15]:
# Creating two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42)# set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 =tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of the elements in a tensor

In [16]:
# shuffle a tensor (valuable for shuffling one's data)

not_shuffled = tf.constant([[10,7],[3,4],[2,5]])

# Shuffled our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [17]:
unshuffled_1 = tf.constant([[1,2],[3,4],[5,6]])
unshuffled_2 = tf.constant([[17,32],[39,47],[57,16]])
unshuffled_3 = tf.constant([[12,21],[33,45],[5,16]])
unshuffled_4 = tf.constant([[12,1],[33,5],[5,116]])

tf.random.set_seed(2)
tf.random.shuffle(unshuffled_4,seed=2)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  5, 116],
       [ 33,   5],
       [ 12,   1]], dtype=int32)>

### Other ways to make tensors

In [18]:
# Create a tensor of all ones
tf.ones([7,10])

<tf.Tensor: shape=(7, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
#Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU computing.

In [20]:
#Turning numpy arrays into tensors

import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
A = tf.constant(numpy_A,shape=(3,8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [22]:
A.ndim

2

### Getting info from tensors

Tensor Attributes should be familiared with:

* Shape
* Rank
* Axis or dimension
* Size

In [23]:
# Create a rank 4 tensor

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
# Get various attributes of tensors

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 Axis:", rank_4_tensor.shape[0])
print("Elements along the last Axis:", rank_4_tensor.shape[-1])
print("Total number of elements:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 Axis: 2
Elements along the last Axis: 5
Total number of elements: 120


### Indexing tensors

Tensors can be indexed like python lists

In [26]:
# Get the first two elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Create a rank 2 tensor (2 dimension)
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [29]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [30]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [31]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) 

# axis=-1 means expand the final axis
# axis=0 means expand the 0th axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operation**

`+`,  `-`,  `*`,  `/`

In [32]:
# You can add values to a tensor using addition operator

tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [33]:
# Multiplication of tensors
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [34]:
# Suntraction of tensors
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [35]:
# We can use the tensorflow built-in functions
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In machine learning matrix multiplication is one of the most common operations

In [36]:
# Matrix multiplication in tensorflow

tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [37]:
# Matrix multiplication with Python operator "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [38]:
# Create a tensor of (3,2)
X = tf.constant([[1,2],[3,4],[5,6]])
# Create a tensor (2,3)
Y = tf.constant([[7,8,1],[9,4,6]])
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[25, 16, 13],
       [57, 40, 27],
       [89, 64, 41]], dtype=int32)>

In [39]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [40]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(X,Y,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[25, 16, 13],
       [57, 40, 27],
       [89, 64, 41]], dtype=int32)>

### Changing the datatype of a tensor

In [41]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [42]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [43]:
# Changing tensor from float32 to float16 (reduced precision)
D=tf.cast(B,dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [44]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [45]:
# Get the absolute values

D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [46]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following form of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [47]:
# Create a random tensor with values between 0 and 100 of size 50

E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([25, 82, 50, 45, 13, 64, 21, 26, 93, 94, 77, 80,  3,  7, 10, 49, 53,
       79, 41, 19, 72, 63, 76, 91, 33, 94, 79, 42,  6, 33, 62, 32, 97, 24,
       93, 50, 86, 94, 56,  5, 66, 68, 62, 18, 27, 36, 57, 70, 66, 25])>

In [48]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [49]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [50]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [51]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2614>

In [52]:
# Find the standard variance of a tensor
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.292784>

In [57]:
# Find the variance of tensor
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=800.48157>

### Find the positional maximum and minimum of a tensor

In [58]:
tf.math.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=32>

In [59]:
tf.math.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=12>

### Squeezing a tensor (removing all single dimensions)

In [62]:
# Create a tensor
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6266953 , 0.99403536, 0.5183847 , 0.7920568 , 0.5299039 ,
          0.11978281, 0.00872111, 0.1873821 , 0.32285976, 0.55054796,
          0.88001335, 0.2940594 , 0.29800344, 0.11837089, 0.85573864,
          0.32819045, 0.7732694 , 0.01268756, 0.18967664, 0.9789933 ,
          0.6267749 , 0.9941807 , 0.559399  , 0.28993154, 0.07608581,
          0.69155455, 0.84872043, 0.573318  , 0.12491918, 0.9521879 ,
          0.55773115, 0.14108741, 0.38573337, 0.7083088 , 0.09366488,
          0.38656926, 0.08879924, 0.5009663 , 0.24924529, 0.7305471 ,
          0.29153574, 0.40659153, 0.36110032, 0.7009026 , 0.8507767 ,
          0.8239684 , 0.1353643 , 0.8596884 , 0.78534627, 0.7977723 ]]]],
      dtype=float32)>

In [63]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6266953 , 0.99403536, 0.5183847 , 0.7920568 , 0.5299039 ,
        0.11978281, 0.00872111, 0.1873821 , 0.32285976, 0.55054796,
        0.88001335, 0.2940594 , 0.29800344, 0.11837089, 0.85573864,
        0.32819045, 0.7732694 , 0.01268756, 0.18967664, 0.9789933 ,
        0.6267749 , 0.9941807 , 0.559399  , 0.28993154, 0.07608581,
        0.69155455, 0.84872043, 0.573318  , 0.12491918, 0.9521879 ,
        0.55773115, 0.14108741, 0.38573337, 0.7083088 , 0.09366488,
        0.38656926, 0.08879924, 0.5009663 , 0.24924529, 0.7305471 ,
        0.29153574, 0.40659153, 0.36110032, 0.7009026 , 0.8507767 ,
        0.8239684 , 0.1353643 , 0.8596884 , 0.78534627, 0.7977723 ],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding in tensor

In [68]:
# Create a list of indices
some_list = [0,1,2,3]

# One hot encode list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [66]:
# Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="Deep learning makes pro",off_value="Pro deep learners know")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Deep learning makes pro', b'Pro deep learners know',
        b'Pro deep learners know', b'Pro deep learners know'],
       [b'Pro deep learners know', b'Deep learning makes pro',
        b'Pro deep learners know', b'Pro deep learners know'],
       [b'Pro deep learners know', b'Pro deep learners know',
        b'Deep learning makes pro', b'Pro deep learners know'],
       [b'Pro deep learners know', b'Pro deep learners know',
        b'Pro deep learners know', b'Deep learning makes pro']],
      dtype=object)>

### Squaring, log, square root

In [70]:
# Create a new tensor
H = tf.range(1,10)

In [72]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [73]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [75]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

In [76]:
# Create a tensor directlt from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [78]:
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [79]:
# Convert a tensor J to NumPy array
J.numpy()

array([ 3.,  7., 10.])

In [81]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)